---
# tasks file for roles/docker

- name: Install prereqs
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name: docker-ce

- name: Get docker-compose
  shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Fix permissions
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes
