version: '2'
services:
  redis:
    restart: always
    image: redis
    volumes:
    - ./data:/data/
    container_name: redis
    command: redis-server --appendonly yes --protected-mode no --save 60 1
  frontend:
    restart: always
    build: ./canarytokens/
    image: thinkst/canarytokens
    links:
     - redis
    env_file:
     - frontend.env
    volumes:
    - ./uploads:/uploads/
    - log-volume:/logs
    container_name: frontend
    command: bash -c "rm frontend.pid; twistd -noy frontend.tac --logger log.logger --pidfile=frontend.pid"
  switchboard:
    build: ./canarytokens/
    restart: always
    image: thinkst/canarytokens
    ports:
     - "53:53"
     - "53:53/udp"
     - "25:25"
    links:
     - redis
    env_file:
     - switchboard.env
    volumes_from:
    - frontend
    container_name: switchboard
    command: bash -c "rm switchboard.pid; twistd -noy switchboard.tac --logger log.logger --pidfile=switchboard.pid"
  nginx:
    restart: always
    image: thinkst/canarytokens_nginx
    build: ./nginx/
    ports:
     - "80:80"
     - "443:443"
    links:
     - frontend
     - switchboard
    container_name: nginx
    command: /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
volumes:
  log-volume:
